const { chromium } = require('../../node_modules/@playwright/test');
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs');
const crypto = require('node:crypto');
const { pathToFileURL } = require('node:url');
const root = __dirname;
const hash = buffer => crypto.createHash('sha256').update(buffer).digest('hex');
(async () => {
  const browser = await chromium.launch({ channel: 'msedge', headless: true });
  const page = await browser.newPage({viewport:{width:1280,height:900}});
  const errors=[];
  page.on('pageerror', error=>errors.push(error.message));
  await page.goto(pathToFileURL(path.join(root,'preview.html')).href);
  assert.equal(await page.locator('.card').count(),80);
  await page.selectOption('#status','encoded');
  const count=await page.locator('.card').count();
  assert.ok(count>=2,'Need at least two actual animations to verify switching');
  const first=page.locator('.card').nth(0), second=page.locator('.card').nth(1);
  await first.locator('button').click();
  await page.waitForTimeout(130);
  const frame1=hash(await first.locator('img').screenshot());
  await page.waitForTimeout(420);
  const frame2=hash(await first.locator('img').screenshot());
  assert.notEqual(frame1,frame2,'The rendered image must really animate');
  await second.locator('button').click();
  assert.ok((await first.locator('img').getAttribute('src')).endsWith('poster.webp'));
  assert.equal(await page.locator('.playing').count(),1);
  await page.click('#pause-all');
  await second.locator('img').evaluate(image => image.decode());
  const paused1=hash(await second.locator('img').screenshot());
  await page.waitForTimeout(420);
  assert.equal(hash(await second.locator('img').screenshot()),paused1,'Pause must show a stable poster');
  await page.screenshot({path:path.join(root,'cache/preview-desktop.png')});
  await page.setViewportSize({width:320,height:760});
  await page.screenshot({path:path.join(root,'cache/preview-mobile.png')});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.selectOption('#status','all');
  await page.fill('#search','死虫');
  assert.equal(await page.locator('.card').count(),1);
  assert.ok((await page.locator('.card h2').innerText()).includes('死虫'));
  assert.equal(await page.locator('.playing').count(),0);
  await page.selectOption('.review-status', 'repair');
  await page.fill('.review-note', '右手腕方向需要核对；保留此备注。');
  await page.reload();
  await page.fill('#search','死虫');
  assert.equal(await page.locator('.review-status').inputValue(), 'repair');
  assert.equal(await page.locator('.review-note').inputValue(), '右手腕方向需要核对；保留此备注。');
  await page.fill('#search', '');
  await page.selectOption('#review-filter', 'repair');
  assert.equal(await page.locator('.card').count(), 1);
  const downloadEvent = page.waitForEvent('download');
  await page.click('#export-review');
  const download = await downloadEvent;
  const exported = JSON.parse(fs.readFileSync(await download.path(), 'utf8'));
  assert.equal(exported.format, 'riji-animation-review');
  assert.equal(exported.items.length, 80);
  const marked = exported.items.find(item => item.index === 73);
  assert.equal(marked.status, 'repair');
  assert.equal(marked.note, '右手腕方向需要核对；保留此备注。');
  assert.match(marked.animationSha256, /^[a-f0-9]{64}$/);
  await page.evaluate(() => {
    const stored = JSON.parse(localStorage.getItem('riji-animation-review-v1'));
    stored['02761201-Dead-Bug_Waist'].sha256 = 'old-animation-version';
    localStorage.setItem('riji-animation-review-v1', JSON.stringify(stored));
  });
  await page.reload();
  await page.fill('#search','死虫');
  assert.equal(await page.locator('.review-status').inputValue(), 'pending', 'Replacement animations require fresh review');
  assert.equal(await page.locator('.review-note').inputValue(), '右手腕方向需要核对；保留此备注。', 'Keep previous notes for rechecking');
  assert.equal(await page.locator('.review-outdated').count(), 1);
  await page.evaluate(() => localStorage.removeItem('riji-animation-review-v1'));
  assert.deepEqual(errors,[]);
  const result={items:80,encodedAtVerification:count,realPlayback:true,singleActiveAnimation:true,pauseStable:true,search:true,viewport320NoOverflow:true,reviewPersisted:true,reviewFilter:true,reviewExport:true,replacementRequiresNewReview:true,pageErrors:errors};
  fs.writeFileSync(path.join(root,'browser-validation.json'),JSON.stringify(result,null,2)+'\n');
  console.log(JSON.stringify(result));
  await browser.close();
})().catch(error=>{console.error(error);process.exit(1)});
